### ISSUE TITLE
 WS Error <Io(Custom { kind: NotConnected, error: StringError("None") })>

### ISSUE THREAD

**Issue by maximov-ru** [steamroller-airmash/airmash-client#1]
I try connecting to  wss://game-eu-s1.airma.sh/ffa2
`2018-11-13 19:37:43 INFO  [airmash_client::message_handler] Starting websocket connection to wss://game-eu-s1.airma.sh/ffa2
2018-11-13 19:37:43 INFO  [ws] Queuing connection to wss://game-eu-s1.airma.sh/ffa2
2018-11-13 19:37:43 ERROR [ws::handler] WS Error <Io(Custom { kind: NotConnected, error: StringError("None") })>
An error occurred:
receiving on a closed channel`

**Comment by steamroller-airmash** [comment]
Sorry for not responding earlier. I didn't get a notification for this :(

Are you running the client on Windows? I get a similar issue and haven't been able to figure out the root cause. 

Looking deeper into the error given seems to suggest that the error is from the client sending packets before the connection is ready (from the docs for `std::io::ErrorKind` [here](https://doc.rust-lang.org/nightly/std/io/enum.ErrorKind.html)).

**Comment by steamroller-airmash** [comment]
Closed since the websocket handling of the client has been changed to use a different library. If the issue opens again this should be reopened as a new issue.
